### PR TITLE
Fix UB of defining stuff in namespace std. Just include the headers.

### LINKED ISSUE #194: Forward-declaring identifiers in std:: is UB - consider including some of the cheaper C/C++ stdlib headers
I noticed that you redefine some stuff that is already part of C and C++ standard library.

For example:

1. You wrap `memcpy` inside `my_memcpy`
2. You redefine `nullptr_t` (which is UB)
3. You forward declare some iostream stuff (again UB).

`cstddef` and `cstring` are two headers that are EXTREMELY common. I can't think of a single non-trivial program that does not already includes these two headers. Just including C++ string or vector brings in these two. So, if some client code has already included them, and Doctest includes them, the second inclusion is practically a no-op because of header include guards.

Therefore, when redefining this stuff, you are optimizing the compile time for the best case, and that is using doctest alone, but you are worsening the common case, which is using doctest to test some other software.

### PR DESCRIPTION
**Pull request by dimztimz**
Having this UB may randomly break just by some compiler update.
Fixes #194

### CODE REVIEW

**Comment by onqtam** [comment]
I can confirm that the code is correct, even though clang gives the ```Wdynamic-class-memaccess``` warning. I'll suppress it.

**Comment by dimztimz** [comment]
I tried with clang and indeed got that warning. Fixing the warning requires header `<new>` which is another cheap header and using placement new.

Suppressing the warning is just hiding more bugs.

**Comment by onqtam** [comment]
When we go down that line... why not get rid of the String class altogether and use std::string? I shouldn't have said that :| Now I'm thinking about it...

**Comment by dimztimz** [comment]
Well, in C++ constructing object with memcpy is UB. The String class is not UB.

**Comment by onqtam** [comment]
regarding the memcpy and <new> - I'm convinced, that's the right way to go indeed.

**Comment by dimztimz** [comment]
No, to be completely correct, memcpy can be used only on trivially copyable types. Otherwise you have UB.

**Comment by dimztimz** [comment]
I will close this as obviously more stuff needs fixing.

**Comment by onqtam** [comment]
It's just that object construction - I'll fixup the code once I get to it.

Here's the deal: I'll work a few more days on the framework and before the release I'll experiment with stdlib headers. I'll most probably merge this.

**Comment by dimztimz** [comment]
OMG this is just frustrating. MSVC 2015 fails for warnings in its own headers.

I can't be bothered to fix this anymore, please just reduce the warning level. MSVS level 4 is known to produce warnings in its own headers, nobody uses that.

**Comment by onqtam** [comment]
@dimztimz :D It's actually not /W4 but /Wall that is used... and I have absolutely no clue as to why I decided to go down that road and suffer.

Anyway don't bother - I'll handle this PR going forward.

**Comment by dimztimz** [comment]
I would suggest you to do the following

1. Reduce the reported warnings to something sane like Wall Wextra on gcc and clang
2. Delete almost all suppresions of warnings. I hace never seen code that wasted 100s of lines just to supress warnibgs.
3. Fix the actual warnings

**Comment by onqtam** [comment]
Someone made a PR where even ```std::tuple``` is forward-declared... https://github.com/onqtam/doctest/pull/203

And in there he uses ```_LIBCPP_BEGIN_NAMESPACE_STD``` so apparently there is an easy way to deal with the inline namespaces of some stdlib implementations. I also found facebook/folly forward-declaring types in the std namespace:
https://github.com/facebook/folly/blob/master/folly/Traits.h#L628

So if Facebook are OK with this kind of UB - then I'm fine with it as well. I'm guessing that if other stdlib implementations (not only libc++) move to inline namespaces they will provide a similar macro.

I will make a compromise however: I'll change [```DOCTEST_CONFIG_USE_IOSFWD```](https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md#doctest_config_use_iosfwd) to something like ```DOCTEST_CONFIG_USE_STD_HEADERS``` and when it is defined - the appropriate std headers will be included (not only for the streams but also for ```nullptr_t```) instead of the forward-declarations. So the only piece of UB left when using that identifier will be the construction of the object with memcpy instead of using placement new.

This has the following benefit for me: I don't have to think about this right now and I'm skipping having to re-do the benchmarks & update the graphs (because the compilation times will have significantly changed) which takes around 1 day...

So I'm closing this PR.

**Comment by dimztimz** [comment]
I'd advise you not to make the code any messier with more config macros.

But I don't really care anymore, I decided not to use doctest at all. The forward declaring is not the only UB. The memcpy you use instead of placement new to construct object is another much dangerous UB. Abd probable there is more ub hidden somewhere.

**Comment by horenmar** [comment]
@dimztimz I think you would be interested in Catch2

**Pull request closed without merging**
